apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-content
  labels:
    app: {{ .Release.Name }}
data:
  default.conf: |
{{ tpl (.Files.Get "files/default.conf") . | indent 4 }}
  index.html: |
{{ .Files.Get "files/index.html" | indent 4 }}
