repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: ["-c", "linters/yamllint.yml"]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        files: ^(scripts/|wireguard/).+\.sh$
  - repo: local
    hooks:
      - id: terraform-fmt-check
        name: terraform fmt check
        entry: terraform fmt -check -recursive terraform
        language: system
        pass_filenames: false
        files: ^terraform/
      - id: tflint-infra-nodes
        name: tflint infra-nodes
        entry: tflint --config linters/tflint.hcl --chdir terraform/infra-nodes
        language: system
        pass_filenames: false
        files: ^terraform/infra-nodes/
      - id: tflint-yandex-vpn
        name: tflint yandex-vpn
        entry: tflint --config linters/tflint.hcl --chdir terraform/yandex-vpn
        language: system
        pass_filenames: false
        files: ^terraform/yandex-vpn/
      - id: ansible-lint-playbooks
        name: ansible-lint playbooks
        entry: ansible-lint -c linters/ansible-lint.yml ansible/playbooks/setup-k3s-server.yml
        language: system
        pass_filenames: false
        files: ^ansible/
