image:
  repository: ghcr.io/sagernet/sing-box
  tag: "v1.13.11"
  pullPolicy: IfNotPresent

sharedHostPath: /var/lib/sing-box-shared
sharedConfigPath: /shared/sing-box/config.json

nodeSelector:
  role: vpn
  channel: prod
  traffic_role: entry

tolerations:
  - key: dedicated
    value: vpn
    effect: NoSchedule

ports:
  vless:
    containerPort: 443
    hostPort: 443
  api:
    containerPort: 9090
    hostPort: 0

reality:
  privateKey: ""
  shortId: ""
  serverName: "www.cloudflare.com"
  handshakeServer: "www.cloudflare.com"
  handshakePort: 443

api:
  externalControllerListen: "127.0.0.1:9090"
  secret: ""

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

logLevel: info
