nodeSelector:
  role: vpn
  channel: dev
  traffic_role: entry-disabled-embedded-cutover

reality:
  privateKey: "2JcSaVDfb3caMQ3-XaNEqfzcHBFLlQ4zmiLcfD0sp2o"
  shortId: "6c1ec52d8fabfd86"
  serverName: "www.cloudflare.com"
  handshakeServer: "www.cloudflare.com"
  handshakePort: 443

ports:
  vless:
    containerPort: 443
    hostPort: 443
  api:
    containerPort: 9090
    hostPort: 0
