services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
    ports:
      - "127.0.0.1:9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    env_file:
      - ../.env
    labels:
      - "traefik.enable=true"

      # Router
      - "traefik.http.routers.grafana.rule=Host(`grafana.lannister-dev.ru`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=cf"
      - "traefik.http.routers.grafana.middlewares=grafana-headers@docker"

      # Service
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

      # Middleware
      - "traefik.http.middlewares.grafana-headers.headers.customRequestHeaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.grafana-headers.headers.customRequestHeaders.X-Forwarded-Port=443"

    volumes:
      - grafana_data:/var/lib/grafana
      - ../monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    networks:
      - traefik_proxy
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro,rslave"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    env_file:
      - ../.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme:/acme
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_proxy"

      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"

      - "--certificatesresolvers.cf.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.cf.acme.email=degterev907@gmail.com"
      - "--certificatesresolvers.cf.acme.storage=/acme/acme.json"
      - "--certificatesresolvers.cf.acme.dnschallenge.provider=cloudflare"

      - "--accesslog=true"
      - "--log.level=INFO"
    labels:
      - traefik.enable=true
      # Router
      - traefik.http.routers.traefik.rule=Host(`traefik.lannister-dev.ru`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=cf
      - traefik.http.routers.traefik.service=api@internal
      # Basic Auth middleware
      - traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$RWsuY3iD$$W3qlQsMXCi0hWoEZf0Kdz/
        # Attach middleware to router
      - traefik.http.routers.traefik.middlewares=traefik-auth@docker
    networks:
      - traefik_proxy

volumes:
  prometheus_data:
  grafana_data:
networks:
  traefik_proxy:
    name: traefik_proxy
    external: true