http:
  routers:
    acme:
      rule: "PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - web
      service: noop@internal
      priority: 100

    harbor-http:
      rule: "Host(`registry.lannister.webtm.ru`)"
      entryPoints:
        - web
      service: harbor
      priority: 1

    harbor-https:
      rule: "Host(`registry.lannister.webtm.ru`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: harbor

  services:
    harbor:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8080"