log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false

certificatesResolvers:
  cloudflare:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: degterev907@gmail.com
      storage: /acme/acme.json
      dnsChallenge:
        provider: cloudflare

tls:
  stores:
    default: {}