[log]
  level = "DEBUG"

[accessLog]
  format = "json"

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.http.redirections.entryPoint]
      to = "https"
      scheme = "https"
      permanent = true

  [entryPoints.https]
    address = ":443"
    [entryPoints.https.http.tls]
      certResolver = "letsEncrypt"

[api]
  dashboard = true
  insecure = true

[providers.docker]
  exposedByDefault = false
  network = "traefik_proxy"

[certificatesResolvers.letsEncrypt.acme]
  email = "degterev907@gmail.com"
  storage = "/ssl/acme.json"
  [certificatesResolvers.letsEncrypt.acme.dnsChallenge]
    provider = "cloudflare"