entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /traefik
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: degterev907@gmail.com
      storage: /acme.json
      dnsChallenge:
        provider: cloudflare
