[log]
  level = "DEBUG"

[accessLog]
  format = "json"

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.http.redirections.entryPoint]
      to = "https"
      scheme = "https"
      permanent = true

  [entryPoints.https]
    address = ":443"

[tls.stores]
  [tls.stores.default]

[api]
  dashboard = true
  insecure = true

[providers.docker]
  exposedByDefault = false
  network = "traefik_proxy"

[certificatesResolvers.letsEncrypt.acme]
  email = "degterev907@gmail.com"
  storage = "/ssl/acme.json"
  [certificatesResolvers.letsEncrypt.acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 0

[providers.file]
  filename = "/certs/dynamic.yml"
  watch = true