[entryPoints]
  [entryPoints.https]
    address = ":443"

[api]
  [api]
  dashboard = true
  insecure = true

[providers.docker]
  exposedByDefault = false
  network = "traefik_proxy"

[certificatesResolvers.letsEncrypt.acme]
  storage = "/ssl/acme.json"
  [certificatesResolvers.letsEncrypt.acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 0