entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

  providers:
    docker:
      exposedByDefault: false

  certificatesResolvers:
    letsencrypt:
      acme:
        email: degterev907@gmail.com
        storage: /acme.json
        httpChallenge:
          entryPoint: web