apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alert-bot-prod-env
  namespace: vpn-prod
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: alert-bot-prod-env
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: alert-bot/prod/env
        metadataPolicy: None
