# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: probe-dev-env
  namespace: vpn-dev
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: probe-dev-env
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: probe/dev/env
        metadataPolicy: None
