{{- if .Values.fallback.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-xray
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    {{- $svc := printf "%s-xray" .Release.Name }}
    {{- if .Values.vpn.xhttpPath }}
    - match: PathPrefix(`{{ .Values.vpn.xhttpPath }}`)
      kind: Rule
      services:
        - name: {{ $svc }}
          port: xhttp
          responseForwarding:
            flushInterval: "1ms"
    {{- end }}
    - match: PathPrefix(`{{ .Values.vpn.wsPath }}`)
      kind: Rule
      services:
        - name: {{ $svc }}
          port: ws
  tls:
    {{- if .Values.vpn.publicHost }}
    certResolver: letsencrypt
    domains:
      - main: {{ .Values.vpn.publicHost }}
    {{- end }}
{{- end }}
