{{- if .Values.fallback.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-xray
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- if .Values.vpn.publicHost }}
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    {{- end }}
spec:
  rules:
    {{- $svc := printf "%s-xray" .Release.Name }}
    {{- $wsPath := .Values.vpn.wsPath }}
    {{- $xhttpPath := .Values.vpn.xhttpPath }}
    {{- if .Values.vpn.publicHost }}
    - host: {{ .Values.vpn.publicHost }}
      http:
        paths:
          - path: {{ $wsPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $svc }}
                port:
                  name: ws
          {{- if $xhttpPath }}
          - path: {{ $xhttpPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $svc }}
                port:
                  name: xhttp
          {{- end }}
    {{- end }}
    - http:
        paths:
          - path: {{ $wsPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $svc }}
                port:
                  name: ws
          {{- if $xhttpPath }}
          - path: {{ $xhttpPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $svc }}
                port:
                  name: xhttp
          {{- end }}
{{- end }}
