{{- if .Values.nodeAgent.bootstrapToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nodeAgent.secretName }}
  labels:
    app: node-agent
    chart: {{ .Chart.Name }}
type: Opaque
data:
  token: {{ .Values.nodeAgent.bootstrapToken | b64enc }}
{{- end }}
{{- if and .Values.warp.enabled .Values.warp.privateKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.warp.secretName }}
  labels:
    app: xray
    chart: {{ .Chart.Name }}
type: Opaque
data:
  privateKey: {{ .Values.warp.privateKey | b64enc }}
{{- end }}
