{{- if .Values.nodeAgent.bootstrapToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nodeAgent.secretName }}
  labels:
    app: node-agent
    chart: {{ .Chart.Name }}
type: Opaque
data:
  token: {{ .Values.nodeAgent.bootstrapToken | b64enc }}
{{- end }}
