global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: "services_important"
    scrape_interval: 15s
    scrape_timeout: 10s

    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
        refresh_interval: 2m

    relabel_configs:
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep

      - source_labels: [__meta_dockerswarm_service_label_prometheus_scrape]
        regex: "true"
        action: keep

      - source_labels: [__meta_dockerswarm_service_label_prometheus_scrape_profile]
        regex: important
        action: keep

      - source_labels:
          - __meta_dockerswarm_service_label_prometheus_app
          - __meta_dockerswarm_service_label_prometheus_env
        regex: '(.+);(.+)'
        replacement: '$1-$2'
        target_label: job

      - source_labels: [__meta_dockerswarm_service_name]
        target_label: service

      - source_labels: [__meta_dockerswarm_service_label_prometheus_app]
        target_label: app
      - source_labels: [__meta_dockerswarm_service_label_prometheus_env]
        target_label: env

      - source_labels: [__meta_dockerswarm_service_label_prometheus_metrics_path]
        regex: '(.+)'
        target_label: __metrics_path__
        action: replace

      - source_labels:
          - __address__
          - __meta_dockerswarm_service_label_prometheus_metrics_port
        regex: '([^:]+)(?::\d+)?;(.*)'
        replacement: '$1:$2'
        target_label: __address__