global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "bot-server"
    static_configs:
     - targets:
        - "212.113.117.153:9100"
        - "212.113.117.153:8080"

  - job_name: "vpn-server"
    static_configs:
     - targets:
        - "185.140.12.144:9100"
        - "185.140.12.144:8080"

  - job_name: "registry-server"
    static_configs:
     - targets:
        - "77.95.206.47:9100"
        - "cadvisor:8080"

  - job_name: 'traefik'
    static_configs:
      - targets:
        - "traefik:8080"