global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "bot-server"
    static_configs:
     - targets:
        - "BOT_IP:9100"
        - "BOT_IP:8080"

  - job_name: "vpn-server"
    static_configs:
     - targets:
        - "VPN_IP:9100"
        - "VPN_IP:8080"

  - job_name: "registry-server"
    static_configs:
     - targets:
        - "127.0.0.1:9100"
        - "127.0.0.1:8080"