---
- name: Deploy {{ stack_name }} stack
  ansible.builtin.command:
    argv: >-
      {{
        ['docker', 'stack', 'deploy']
        + (['--with-registry-auth'] if with_registry_auth else [])
        + extra_deploy_args
        + ['-c', compose_file, stack_name]
      }}
  args:
    chdir: "{{ repo_root }}"
  environment: "{{ stack_environment }}"
  changed_when: false
