http:
  middlewares:
    harbor-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Host: "harbor.lannister-dev.ru"

  routers:
    harbor:
      rule: "Host(`harbor.lannister-dev.ru`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cf
      middlewares:
        - harbor-headers
      service: harbor

  services:
    harbor:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:8081"