http:
  routers:
    vpn-ws:
      rule: "Host(`vpn.lannister-dev.ru`) && PathPrefix(`/api/v1/stream`)"
      entryPoints: [websecure]
      tls:
        certResolver: cf
      service: vpn-upstream

    vpn-site:
      rule: "Host(`vpn.lannister-dev.ru`)"
      entryPoints: [websecure]
      tls:
        certResolver: cf
      service: vpn-fallback

  services:
    vpn-upstream:
      loadBalancer:
        servers:
          - url: "http://10.100.0.2:10000"

    vpn-fallback:
      loadBalancer:
        servers:
          - url: "http://vpn-fallback:80"