apiVersion: v1
kind: Service
metadata:
  name: postgres-dev
  namespace: vpn-dev
spec:
  type: ExternalName
  externalName: data-dev-postgres.data-dev.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: redis-dev
  namespace: vpn-dev
spec:
  type: ExternalName
  externalName: data-dev-redis.data-dev.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-prod
  namespace: vpn-prod
spec:
  type: ExternalName
  externalName: data-prod-postgres.data-prod.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: redis-prod
  namespace: vpn-prod
spec:
  type: ExternalName
  externalName: data-prod-redis.data-prod.svc.cluster.local
