version: "3.9"

# ======= deploy services =========
x-deploy-common: &deploy-common
  replicas: 1
  update_config:
    parallelism: 1
    delay: 10s
    order: start-first
    failure_action: rollback
  restart_policy:
    condition: on-failure
    max_attempts: 3

services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    deploy:
      <<: *deploy-common
      placement:
        constraints:
          - node.role == manager
    volumes:
      - prometheus_data:/prometheus
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:9090/-/healthy" ]
      interval: 10s
      timeout: 5s
      retries: 3

    networks:
      - traefik_proxy

  grafana:
    image: grafana/grafana:latest
    env_file:
      - ../../.env
    configs:
      - source: grafana_ini
        target: /etc/grafana/grafana.ini
      - source: grafana_datasources
        target: /etc/grafana/provisioning/datasources/prometheus.yml
      - source: grafana_dashboards
        target: /etc/grafana/provisioning/dashboards/dashboards.yml
    deploy:
      <<: *deploy-common
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.lannister-dev.ru`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.service=grafana"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    volumes:
      - grafana_data:/var/lib/grafana
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - traefik_proxy

  node-exporter:
    image: prom/node-exporter:latest
    deploy:
      mode: global
    ports:
      - target: 9100
        published: 9100
        protocol: tcp
        mode: host
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro,rslave"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    deploy:
      mode: global
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
configs:
  prometheus_config:
    external: true
  grafana_ini:
    external: true
  grafana_datasources:
    external: true
  grafana_dashboards:
    external: true

volumes:
  prometheus_data:
  grafana_data:

networks:
  traefik_proxy:
    external: true
    name: traefik_swarm