---
services:
  nats:
    image: nats:${NATS_IMAGE_TAG}
    command:
      - /bin/sh
      - -ec
      - >-
        exec nats-server
        --jetstream
        --store_dir=/data
        --http_port=8222
        --server_name=nats
        --auth "$$(cat /run/secrets/nats_auth_token)"
    volumes:
      - nats_data:/data
    secrets:
      - nats_auth_token
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.kind == dev
      update_config:
        order: stop-first
        failure_action: rollback
      rollback_config:
        order: stop-first
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nats.rule=Host(`nats.lannister-dev.ru`)"
        - "traefik.http.routers.nats.entrypoints=websecure"
        - "traefik.http.routers.nats.tls=true"
        - "traefik.http.routers.nats.service=nats"
        - "traefik.http.routers.nats.middlewares=nats-auth@swarm"
        - "traefik.http.services.nats.loadbalancer.server.port=8222"
        - "traefik.http.middlewares.nats-auth.basicauth.users=admin:$$apr1$$pJrubxMY$$Dvvcwt08XWViGWk/21qv9/"
        #TCP
        - "traefik.tcp.routers.nats-client.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.nats-client.entrypoints=nats"
        - "traefik.tcp.routers.nats-client.service=nats-client-svc"
        - "traefik.tcp.services.nats-client-svc.loadbalancer.server.port=4222"
    networks:
      vpn-net:
        aliases:
          - nats
      monitoring:
      traefik_swarm:

  nats-exporter:
    image: natsio/prometheus-nats-exporter:${NATS_EXPORTER_IMAGE_TAG}
    command:
      - "-varz"
      - "-connz"
      - "-routez"
      - "-subz"
      - "-jsz=all"
      - "http://nats:8222"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.kind == dev
      restart_policy:
        condition: any
      labels:
        - "prometheus-scrape=true"
        - "prometheus-app=nats"
        - "prometheus-env=dev"
        - "prometheus-metrics-port=7777"
        - "prometheus-metrics-path=/metrics"
        - "prometheus-scrape-profile=important"
    networks:
      - monitoring

volumes:
  nats_data:
    driver: local

networks:
  monitoring:
    external: true
  vpn-net:
    external: true
  traefik_swarm:
    external: true

secrets:
  nats_auth_token:
    external: true
