version: "3.9"

services:
  traefik:
    image: traefik:v3.4

    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    env_file:
      - ../../.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_acme:/acme
      - /opt/vpn-infra/docker/traefik/dynamic:/dynamic:ro
    command:
      # ENTRYPOINTS
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certresolver=cf"

      # PROVIDERS
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=traefik_swarm"
      - "--providers.swarm.watch=true"
      - "--providers.file.directory=/dynamic"
      - "--providers.file.watch=true"

      # API / DASHBOARD
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--ping=true"

      # ACME (DNS-01)
      - "--certificatesresolvers.cf.acme.email=degterev907@gmail.com"
      - "--certificatesresolvers.cf.acme.storage=/acme/acme.json"
      - "--certificatesresolvers.cf.acme.dnschallenge.provider=cloudflare"

      # METRICS
      - "--metrics.prometheus=true"

      # LOGGING
      - "--accesslog=true"
      - "--log.level=INFO"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"

        # ============ TRAEFIK DASHBOARD ================
        - "traefik.http.routers.traefik.rule=Host(`traefik.lannister-dev.ru`)"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"

        # ============ BASIC AUTH =======================
        - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$apr1$RWsuY3iD$W3qlQsMXCi0hWoEZf0Kdz/"
        - "traefik.http.routers.traefik.middlewares=dashboard-auth@swarm"

        # ===== PROMETHEUS =====
        - "prometheus-scrape=true"
        - "prometheus-app=traefik"
        - "prometheus-env=monitoring"
        - "prometheus-metrics-port=8080"
        - "prometheus-scrape-profile=important"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

    networks:
      - traefik_proxy

volumes:
  traefik_acme:

networks:
  traefik_proxy:
    external: true
    name: traefik_swarm
    driver: overlay
    attachable: true