---
x-deploy-common: &deploy-common
  mode: replicated
  replicas: 1
  update_config:
    order: stop-first
    monitor: 60s
    failure_action: rollback
  rollback_config:
    order: stop-first
    monitor: 60s
  restart_policy:
    condition: any

services:
  vault:
    image: vault:${VAULT_IMAGE_TAG:-1.13.3}
    user: "0:0"
    cap_add:
      - IPC_LOCK
    command:
      - server
      - -config=/vault/config/vault.hcl
    networks:
      - traefik_proxy
      - monitoring
      - vpn-net
    volumes:
      - vault_data:/vault/data
    configs:
      - source: vault_config
        target: /vault/config/vault.hcl
        mode: 292
    deploy:
      <<: *deploy-common
      placement:
        constraints:
          - node.role == manager
          - node.labels.kind == dev
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_swarm"
        - "traefik.http.routers.vault.rule=Host(`vault.lannister-dev.ru`)"
        - "traefik.http.routers.vault.entrypoints=websecure"
        - "traefik.http.routers.vault.tls=true"
        - "traefik.http.routers.vault.tls.certresolver=cf"
        - "traefik.http.routers.vault.service=vault"
        - "traefik.http.services.vault.loadbalancer.server.port=8200"


volumes:
  vault_data:
    driver: local

networks:
  traefik_proxy:
    external: true
    name: traefik_swarm
  monitoring:
    external: true
  vpn-net:
    external: true

configs:
  vault_config:
    external: true
    name: ${VAULT_CONFIG_NAME}
