apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
data:
  config.json: |
    {
      "log": { "level": {{ .Values.logLevel | quote }}, "timestamp": true },
      "experimental": {
        "clash_api": {
          "external_controller": {{ .Values.api.externalControllerListen | quote }}{{ if .Values.api.secret }},
          "secret": {{ .Values.api.secret | quote }}{{ end }}
        }
      },
      "inbounds": [
        {
          "type": "vless",
          "tag": "vless-reality-in",
          "listen": "0.0.0.0",
          "listen_port": {{ .Values.ports.vless.containerPort }},
          "users": [],
          "tls": {
            "enabled": true,
            "server_name": {{ .Values.reality.serverName | quote }},
            "reality": {
              "enabled": true,
              "handshake": {
                "server": {{ .Values.reality.handshakeServer | quote }},
                "server_port": {{ .Values.reality.handshakePort }}
              },
              "private_key": {{ .Values.reality.privateKey | quote }},
              "short_id": [{{ .Values.reality.shortId | quote }}]
            }
          }
        }
      ],
      "outbounds": [
        { "type": "direct", "tag": "direct" },
        { "type": "block",  "tag": "block"  }
      ],
      "route": {
        "rules": [],
        "final": "direct"
      }
    }
