apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: whitelist-entry-relay
    chart: {{ .Chart.Name }}
data:
  haproxy.cfg: |
    global
      log stdout format raw local0

    defaults
      log global
      mode tcp
      option tcplog
      timeout connect 10s
      timeout client 1m
      timeout server 1m

    frontend fe_tls
      bind :443
      default_backend be_tls

    backend be_tls
      server upstream {{ .Values.upstream }} check
