apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app: whitelist-entry-relay
    chart: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: whitelist-entry-relay
  template:
    metadata:
      labels:
        app: whitelist-entry-relay
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: haproxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: tls
              containerPort: 443
              hostPort: 443
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            exec:
              command: ["haproxy", "-c", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            exec:
              command: ["haproxy", "-c", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
